import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { BarChart3, Sparkles } from "lucide-react";
import type { PredictionResult } from "./IrrigationPredictionResult";

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

const CLASS_CONFIG = {
  Low: {
    label: "Low Irrigation",
    barColor: "bg-emerald-500",
    textColor: "text-emerald-600 dark:text-emerald-400",
    dotColor: "bg-emerald-500",
  },
  Medium: {
    label: "Medium Irrigation",
    barColor: "bg-amber-500",
    textColor: "text-amber-600 dark:text-amber-400",
    dotColor: "bg-amber-500",
  },
  High: {
    label: "High Irrigation",
    barColor: "bg-rose-500",
    textColor: "text-rose-600 dark:text-rose-400",
    dotColor: "bg-rose-500",
  },
} as const;

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

interface Props {
  result: PredictionResult;
}

export default function IrrigationChart({ result }: Props) {
  const { probabilities, irrigation_need } = result;
  const classes = ["Low", "Medium", "High"] as const;

  return (
    <Card className="shadow-sm border transition-all duration-300 hover:shadow-md">
      <CardHeader className="pb-3 border-b border-border/50">
        <div className="flex items-center justify-between">
          <CardTitle className="text-base font-semibold flex items-center gap-2">
            <BarChart3 className="h-5 w-5 text-indigo-500" />
            <span>Prediction Probabilities</span>
          </CardTitle>
          <span className="text-xs text-muted-foreground font-mono">
            Σ = 100%
          </span>
        </div>
      </CardHeader>
      <CardContent className="pt-6 space-y-5">
        {classes.map((cls) => {
          const rawPct = (probabilities[cls] || 0) * 100;
          const pct = Math.round(rawPct);
          const isSelected = cls === irrigation_need;
          const cfg = CLASS_CONFIG[cls];

          return (
            <div
              key={cls}
              className={`p-3 rounded-lg border transition-all ${
                isSelected
                  ? "bg-accent/40 border-primary/20 shadow-xs"
                  : "bg-background/50 border-border/40"
              }`}
            >
              <div className="flex items-center justify-between text-sm font-medium mb-2">
                <div className="flex items-center gap-2">
                  <span className={`h-2.5 w-2.5 rounded-full ${cfg.dotColor}`} />
                  <span className={isSelected ? "font-bold text-foreground" : "text-muted-foreground"}>
                    {cls}
                  </span>
                  {isSelected && (
                    <Badge variant="secondary" className="text-[10px] px-1.5 py-0 h-4 flex items-center gap-1 font-semibold">
                      <Sparkles className="h-2.5 w-2.5 text-primary" />
                      Predicted
                    </Badge>
                  )}
                </div>
                <span className={`font-mono text-sm tabular-nums font-bold ${cfg.textColor}`}>
                  {pct}%
                </span>
              </div>

              {/* Bar track */}
              <div className="h-3 w-full overflow-hidden rounded-full bg-muted/80 p-0.5">
                <div
                  className={`h-full rounded-full transition-all duration-700 ease-out ${cfg.barColor}`}
                  style={{
                    width: `${Math.max(pct, pct > 0 ? 3 : 0)}%`,
                  }}
                />
              </div>
            </div>
          );
        })}

        <div className="pt-2 text-center">
          <p className="text-xs text-muted-foreground">
            Class distribution generated by Random Forest (ranger) ensemble model
          </p>
        </div>
      </CardContent>
    </Card>
  );
}
